/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as BeanIndexRouteImport } from './routes/bean/index'
import { Route as TableTableItemIdRouteImport } from './routes/table/$tableItemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeanIndexRoute = BeanIndexRouteImport.update({
  id: '/bean/',
  path: '/bean/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableItemIdRoute = TableTableItemIdRouteImport.update({
  id: '/table/$tableItemId',
  path: '/table/$tableItemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table/$tableItemId': typeof TableTableItemIdRoute
  '/bean': typeof BeanIndexRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/table/$tableItemId': typeof TableTableItemIdRoute
  '/bean': typeof BeanIndexRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/table/$tableItemId': typeof TableTableItemIdRoute
  '/bean/': typeof BeanIndexRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/table/$tableItemId' | '/bean' | '/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table/$tableItemId' | '/bean' | '/table'
  id: '__root__' | '/' | '/table/$tableItemId' | '/bean/' | '/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableTableItemIdRoute: typeof TableTableItemIdRoute
  BeanIndexRoute: typeof BeanIndexRoute
  TableIndexRoute: typeof TableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bean/': {
      id: '/bean/'
      path: '/bean'
      fullPath: '/bean'
      preLoaderRoute: typeof BeanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableItemId': {
      id: '/table/$tableItemId'
      path: '/table/$tableItemId'
      fullPath: '/table/$tableItemId'
      preLoaderRoute: typeof TableTableItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableTableItemIdRoute: TableTableItemIdRoute,
  BeanIndexRoute: BeanIndexRoute,
  TableIndexRoute: TableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
